import dealsone from "@/image/spacalDeals/dealsone.png";
import dealstwo from "@/image/spacalDeals/dealstwo.jpg";
import dealsthree from "@/image/spacalDeals/dealsthree.jpg";
import dealsfour from "@/image/spacalDeals/dealsfour.png";
import dealsfive from "@/image/spacalDeals/dealsfive.png";
import dealssix from "@/image/spacalDeals/dealssix.jpg";
import dealsseven from "@/image/spacalDeals/dealsseven.jpg";
export const spatialDealsArray = [
  { title: "Eid Deals - Daily Accessories", image: dealsone },
  { title: "Eid Deals - Gadget Festivals", image: dealstwo },
  { title: "Eid Deals - Flash Sale", image: dealsthree },
  { title: "Eid Deals - Eid Deals - Eid Glamour", image: dealsfour },
  { title: "Eid Deals - Winning Wear Specials", image: dealsfive },
  { title: "Eid Deals - Eid Bazar", image: dealssix },
  { title: "Eid Deals - Gadget Festivals", image: dealsseven },
];
// district array
export const districtArray = [
  {
    district: "Bagerhat",
    upazila: [
      "Bagerhat Sadar",
      "Chitalmari",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
    ],
  },
  {
    district: "Bandarban",
    upazila: ["Bandarban Sadar", "Thanchi", "Ruma", "Lama"],
  },
  {
    district: "Barguna",
    upazila: ["Amtali", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"],
  },
  {
    district: "Barishal",
    upazila: [
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gaurnadi",
      "Hizla",
      "Barisal Sadar",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
    ],
  },
  {
    district: "Bhola",
    upazila: [
      "Bhola Sadar",
      "Burhanuddin",
      "Char Fasson",
      "Daulatkhan",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
  },
  {
    district: "Bogura",
    upazila: [
      "Adamdighi",
      "Bogura Sadar",
      "Dhunat",
      "Gabtali",
      "Kahalu",
      "Nandigram",
      "Shibganj",
      "Sonatola",
    ],
  },
  {
    district: "Brahmanbaria",
    upazila: [
      "Akhaura",
      "Ashuganj",
      "Bancharampur",
      "Brahmanbaria Sadar",
      "Kasba",
      "Nabinagar",
      "Nasirnagar",
      "Sarail",
    ],
  },
  {
    district: "Chandpur",
    upazila: [
      "Chandpur Sadar",
      "Faridganj",
      "Hajiganj",
      "Matlab Dakshin",
      "Matlab Uttar",
      "Shahrasti",
      "Kachua",
      "Haimchar",
    ],
  },
  {
    district: "Chattogram",
    upazila: [
      "Anwara",
      "Banshkhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
    ],
  },
  {
    district: "Chuadanga",
    upazila: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  },
  {
    district: "Comilla",
    upazila: [
      "Barura",
      "Brahmanpara",
      "Burichong",
      "Chandina",
      "Chauddagram",
      "Cumilla Sadar Dakshin",
      "Cumilla Sadar Uttar",
      "Debidwar",
      "Daudkandi",
      "Homna",
      "Meghna",
      "Muradnagar",
      "Nangalkot",
      "Titas",
    ],
  },
  {
    district: "Coxs Bazar",
    upazila: [
      "Chakaria",
      "Coxs Bazar Sadar",
      "Kutubdia",
      "Maheshkhali",
      "Ramu",
      "Teknaf",
      "Ukhia",
    ],
  },
  {
    district: "Dhaka",
    upazila: ["Dhamrai", "Dohar", "Dhaka", "Keraniganj", "Nawabganj", "Savar"],
  },
  {
    district: "Dinajpur",
    upazila: [
      "Birol",
      "Birganj",
      "Birampur",
      "Bochaganj",
      "Chirirbandar",
      "Dinajpur Sadar",
      "Ghoraghat",
      "Hakimpur",
      "Khansama",
      "Nawabganj",
      "Parbatipur",
    ],
  },
  {
    district: "Faridpur",
    upazila: [
      "Alfadanga",
      "Bhanga",
      "Boalmari",
      "Charbhadrasan",
      "Faridpur Sadar",
      "Madhukhali",
      "Nagarkanda",
      "Sadarpur",
      "Saltha",
    ],
  },
  {
    district: "Feni",
    upazila: [
      "Chhagalnaiya",
      "Daganbhuiyan",
      "Feni Sadar",
      "Fulgazi",
      "Parshuram",
    ],
  },
  {
    district: "Gaibandha",
    upazila: [
      "Fulchhari",
      "Gaibandha Sadar",
      "Gobindaganj",
      "Palashbari",
      "Sadullapur",
      "Sundarganj",
    ],
  },
  {
    district: "Gazipur",
    upazila: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
  },
  {
    district: "Gopalganj",
    upazila: [
      "Gopalganj Sadar",
      "Kashiani",
      "Kotalipara",
      "Muksudpur",
      "Tungipara",
    ],
  },
  {
    district: "Habiganj",
    upazila: [
      "Bahubal",
      "Baniachang",
      "Chunarughat",
      "Habiganj Sadar",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
    ],
  },
  {
    district: "Jamalpur",
    upazila: [
      "Bakshiganj",
      "Dewanganj",
      "Islampur",
      "Jamalpur Sadar",
      "Madarganj",
      "Melandaha",
      "Sarishabari",
    ],
  },
  {
    district: "Jashore",
    upazila: [
      "Abhaynagar",
      "Bagherpara",
      "Chowgacha",
      "Jhikargachha",
      "Jashore Sadar",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
  },
  {
    district: "Jhalokati",
    upazila: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  },
  {
    district: "Jhenaidah",
    upazila: [
      "Harinakundu",
      "Jhenaidah Sadar",
      "Kaliganj",
      "Kotchandpur",
      "Maheshpur",
      "Shailkupa",
    ],
  },
  {
    district: "Joypurhat",
    upazila: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  },
  {
    district: "Khagrachhari",
    upazila: [
      "Dighinala",
      "Khagrachhari Sadar",
      "Lakshmichhari",
      "Mahalchhari",
      "Manikchhari",
      "Matiranga",
      "Panchhari",
      "Ramgarh",
    ],
  },
  {
    district: "Khulna",
    upazila: [
      "Batiaghata",
      "Dacope",
      "Daulatpur",
      "Dumuria",
      "Khan Jahan Ali",
      "Koyra",
      "Paikgachha",
      "Phultala",
      "Rupsha",
      "Terokhada",
    ],
  },
  {
    district: "Kishoreganj",
    upazila: [
      "Austagram",
      "Bajitpur",
      "Bhairab",
      "Hossainpur",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kishoreganj Sadar",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
    ],
  },
  {
    district: "Kurigram",
    upazila: [
      "Bhurungamari",
      "Char Rajibpur",
      "Chilmari",
      "Fulbari",
      "Kurigram Sadar",
      "Nageshwari",
      "Rajarhat",
      "Ulipur",
    ],
  },
  {
    district: "Kushtia",
    upazila: [
      "Bheramara",
      "Daulatpur",
      "Khoksa",
      "Kumarkhali",
      "Kushtia Sadar",
    ],
  },
  {
    district: "Lakshmipur",
    upazila: ["Kamalnagar", "Lakshmipur Sadar", "Ramganj", "Raipur", "Ramgati"],
  },
  {
    district: "Lalmonirhat",
    upazila: [
      "Aditmari",
      "Hatibandha",
      "Kaliganj",
      "Lalmonirhat Sadar",
      "Patgram",
    ],
  },
  {
    district: "Madaripur",
    upazila: ["Kalkini", "Madaripur Sadar", "Rajoir"],
  },
  {
    district: "Magura",
    upazila: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  },
  {
    district: "Manikganj",
    upazila: [
      "Daulatpur",
      "Ghior",
      "Harirampur",
      "Manikganj Sadar",
      "Saturia",
      "Shibaloy",
    ],
  },
  {
    district: "Meherpur",
    upazila: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  },
  {
    district: "Moulvibazar",
    upazila: [
      "Barlekha",
      "Juri",
      "Kamalganj",
      "Kulaura",
      "Moulvibazar Sadar",
      "Rajnagar",
      "Sreemangal",
    ],
  },
  {
    district: "Munshiganj",
    upazila: [
      "Gazaria",
      "Lohajang",
      "Munshiganj Sadar",
      "Sirajdikhan",
      "Sreenagar",
      "Tongibari",
    ],
  },
  {
    district: "Mymensingh",
    upazila: [
      "Bhaluka",
      "Dhobaura",
      "Fulbaria",
      "Gaffargaon",
      "Gauripur",
      "Haluaghat",
      "Ishwarganj",
      "Mymensingh Sadar",
      "Muktagacha",
      "Nandail",
      "Phulpur",
      "Tarakanda",
    ],
  },
  {
    district: "Naogaon",
    upazila: [
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Mahadebpur",
      "Naogaon Sadar",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
  },
  { district: "Narail", upazila: ["Kalia", "Lohagara", "Narail Sadar"] },
  {
    district: "Narayanganj",
    upazila: [
      "Araihazar",
      "Bandar",
      "Narayanganj Sadar",
      "Rupganj",
      "Sonargaon",
    ],
  },
  {
    district: "Narsingdi",
    upazila: [
      "Belabo",
      "Monohardi",
      "Narsingdi Sadar",
      "Palash",
      "Raipura",
      "Shibpur",
    ],
  },
  {
    district: "Natore",
    upazila: [
      "Bagatipara",
      "Baraigram",
      "Gurudaspur",
      "Lalpur",
      "Naldanga",
      "Natore Sadar",
      "Singra",
    ],
  },
  {
    district: "Netrokona",
    upazila: [
      "Atpara",
      "Barhatta",
      "Durgapur",
      "Kalmakanda",
      "Kendua",
      "Khaliajuri",
      "Madan",
      "Mohanganj",
      "Netrokona Sadar",
      "Purbadhala",
    ],
  },
  {
    district: "Nilphamari",
    upazila: [
      "Dimla",
      "Domar",
      "Jaldhaka",
      "Kishoreganj",
      "Nilphamari Sadar",
      "Saidpur",
    ],
  },
  {
    district: "Noakhali",
    upazila: [
      "Begumganj",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Noakhali Sadar",
      "Senbagh",
      "Subarnachar",
    ],
  },
  {
    district: "Pabna",
    upazila: [
      "Atgharia",
      "Bera",
      "Bhangura",
      "Chatmohar",
      "Faridpur",
      "Ishwardi",
      "Pabna Sadar",
      "Santhia",
      "Sujanagar",
    ],
  },
  {
    district: "Panchagarh",
    upazila: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  },
  {
    district: "Patuakhali",
    upazila: [
      "Bauphal",
      "Dashmina",
      "Dumki",
      "Galachipa",
      "Kalapara",
      "Mirzaganj",
      "Patuakhali Sadar",
      "Rangabali",
    ],
  },
  {
    district: "Pirojpur",
    upazila: [
      "Bhandaria",
      "Kawkhali",
      "Mathbaria",
      "Nazirpur",
      "Pirojpur Sadar",
      "Nesarabad",
    ],
  },
  {
    district: "Rajbari",
    upazila: ["Baliakandi", "Goalandaghat", "Pangsha", "Rajbari Sadar"],
  },
  {
    district: "Rajshahi",
    upazila: [
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Paba",
      "Puthia",
      "Rajshahi Sadar",
      "Tanore",
    ],
  },
  {
    district: "Rangamati",
    upazila: [
      "Baghaichhari",
      "Barkal",
      "Kaptai",
      "Juraichhari",
      "Langadu",
      "Naniarchar",
      "Rangamati Sadar",
    ],
  },
  {
    district: "Rangpur",
    upazila: [
      "Badarganj",
      "Gangachara",
      "Kaunia",
      "Mithapukur",
      "Pirgachha",
      "Pirganj",
      "Rangpur Sadar",
      "Taraganj",
    ],
  },
  {
    district: "Satkhira",
    upazila: [
      "Assasuni",
      "Debhata",
      "Kaliganj",
      "Kalaroa",
      "Satkhira Sadar",
      "Shyamnagar",
      "Tala",
    ],
  },
  {
    district: "Shariatpur",
    upazila: [
      "Bhedarganj",
      "Damudya",
      "Gosairhat",
      "Naria",
      "Shariatpur Sadar",
      "Zajira",
    ],
  },
  {
    district: "Sherpur",
    upazila: ["Jhenaigati", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
  },
  {
    district: "Sirajganj",
    upazila: [
      "Belkuchi",
      "Chauhali",
      "Kamarkhanda",
      "Kazipur",
      "Raiganj",
      "Shahjadpur",
      "Sirajganj Sadar",
      "Tarash",
      "Ullahpara",
    ],
  },
  {
    district: "Sunamganj",
    upazila: [
      "Bishwamvarpur",
      "Chhatak",
      "Derai",
      "Dharmapasha",
      "Dowarabazar",
      "Jagannathpur",
      "Jamalganj",
      "Sunamganj Sadar",
      "Tahirpur",
    ],
  },
  {
    district: "Sylhet",
    upazila: [
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Zakiganj",
      "Sylhet Sadar",
    ],
  },
  {
    district: "Tangail",
    upazila: [
      "Basail",
      "Bhuapur",
      "Delduar",
      "Dhanbari",
      "Gopalpur",
      "Kalihati",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Sakhipur",
      "Tangail Sadar",
    ],
  },
  {
    district: "Thakurgaon",
    upazila: [
      "Baliadangi",
      "Haripur",
      "Pirganj",
      "Rani Sankail",
      "Thakurgaon Sadar",
    ],
  },
];
// product categories
export const productCategoriesArray = [
  "Books",
  "Baby Products",
  "Beauty & Personal Care",
  "Clothing",
  "Digital Products",
  "Electronics",
  "Food",
  "Furniture",
  "Gifts & Occasions",
  "Grocery",
  "Garden & Outdoor Living",
  "Handmade",
  "Home & Kitchen",
  "Health & Wellness",
  "Industrial & Scientific",
  "Jewelry",
  "mobile",
  "Movies & Music",
  "Pet Supplies",
  "Sports",
  "Toys & Games",
  "Tools & Home Improvement",
];
// product weight
export const productWeight = [
  { weight: "Under 2 KG", charge: [0, 0] },
  { weight: "2-5 KG", charge: [10, 20] },
  { weight: "5-10 KG", charge: [25, 50] },
  { weight: "10-15 KG", charge: [40, 70] },
  { weight: "15-25 KG", charge: [100, 170] },
  { weight: "25-40 KG", charge: [250, 400] },
  { weight: "40-60 KG", charge: [430, 550] },
];

// admin email array
export const adminArray = ["Hiron@gmail.com","sanaullah@gmail.com"];
